# SPDX-FileCopyrightText: 2026 Kerstin Humm <kerstin@erictapen.name>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
edition = "2024"

name = "rubadan"
version = "0.1.0"
description = "A GUI import tool for hledger (a plain text accounting tool), usable on the web and on desktop."
license = "GPL-3.0-or-later"
repository = "https://github.com/erictapen/rubadan"

[features]
default = []
demo = []


[dependencies]
egui = { version = "*" }
epaint = { version = "*", default-features = false }
egui_extras = { version = "*", default-features = false }
emath = { version = "*", default-features = false }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
log = "*"
rfd = "*"
mt940 = "*"
rust_decimal = "*"
iban = "*"
strum = "*"
strum_macros = "*"
chrono = "*"
indexmap = "*"
nom = "*"


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "*"
eframe = { version = "*", default-features = false, features = [ "persistence", "wayland", "glow", "x11" ] }
futures = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "=0.2.126" }
wasm-bindgen-futures = { version = "*", default-features = false }
web-sys = { version = "*", default-features = false }
eframe = { version = "*", default-features = false, features = [ "persistence", "glow" ] }

[profile.release]
opt-level = 2
